export interface Result {
  ToplistType?: string,
  adType?: number,
  backgroundCoverId?: number,
  backgroundCoverUrl?: string,
  cloudTrackCount?: number,
  commentCount?: number,
  commentThreadId?: string,
  coverImgId?: number,
  coverImgId_str?: string,
  coverImgUrl?: string,
  createTime?: number,
  creator?: any,
  description?: string,
  englishTitle?: string,
  highQuality?: false
  id?: number,
  name?: string,
  newImported?: boolean,
  opRecommendv?: boolean,
  ordered?: boolean,
  playCount?:number,
  privacy?: number,
  remixVideo?: string,
  shareCount?: number,
  sharedUsers?: string,
  specialType?: number,
  status?:number,
  subscribed?: string,
  subscribedCount?: number,
  subscribers?: any,
  tags?: any[],
  titleImage?: number,
  titleImageUrl?: string,
  trackCount?: number,
  trackIds?: any[],
  trackNumberUpdateTime?: number,
  trackUpdateTime?: number,
  tracks?: any[],
  updateFrequency?: string,
  updateTime?: number,
  userId?: number,
  videoIds?: number,
  videos?: string,
}
